---
title: "First Knit"
author: "Anthony Martinez"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended high school at Quartz Hill,and I graduated in the year 2020. In my opinion English comes easier than Math. I feel this way because I have an easier time answering prompts than memorizing formulas. I did the best in English and History. I feel as though both subjects go hand in hand in the nature of the course work.


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live? 

### my answer   
I have an mac laptop that runs macOs 13.3. I would rate myself a 5 or 6 because I am capable of learning how to use and operate certai apps but I do not possess the knowledge nor am I interested on my own. My internet works pretty well. 

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer 
I go by Anthony and prefer to be called by that. 



## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
My biggest goal is to have my band be successful and to be able to travel and play music. Outside of that I am an Anthropology major and would like to get my Doctorate if the music never pulls through. 
  

## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  I have been to Mexico twice and loved it, I really hope to go again one day. I would also like to go to Japan. If I were to get drafted I would most likely choose the Marines because I have family who served in the Marines and I also align more with there methods of operation. 

## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




